### ISSUE TITLE
Node not included in worker container

### ISSUE THREAD

**Issue by dampersand** [gamonoid/icehrm#362]
Using the payroll module and trying to troubleshoot why a payroll column using advanced calculation only returns 0 (note: it's a simple payroll column with an advanced calculation that literally just says "2 + 2").

Found this in the debug logs whenever the advanced calculation runner tries to run:

`sh: node: not found`

exec'd into the docker container for worker and ran `apk add nodejs --update` which successfully installed node.  Now I'm seeing:

```
Error: Cannot find module '/var/www/html/core/execute/execute.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:931:15)
    at Function.Module._load (internal/modules/cjs/loader.js:774:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

Sure enough, after exec'ing into the container:
```
/var/www/html # find . -print | grep execute
/var/www/html #
```

```
/ # find . -print | grep "execute.js"
/ #
```

If execute.js literally is not packed into the container, is it safe to assume advanced calculations on payroll just doesn't work anymore?

**Comment by ddave001** [comment]
Fixed with https://github.com/gamonoid/icehrm/releases/tag/v36.0.0
