### ISSUE TITLE
Error on fresh install; Something wrong with calling SetFetchMode function

### ISSUE THREAD

**Issue by professormahi** [gamonoid/icehrm#47]
I've installed it on an ubuntu 16.04 but it gave me 500 on login page calling.
Here is the errors:

```
init log[03-Jul-2017 10:54:59 Asia/Colombo] PHP Fatal error:  Uncaught Error: Call to a member function SetFetchMode() on boolean in /var/www/hrm/adodb512/adodb-active-record.inc.php:405
Stack trace:
#0 /var/www/hrm/adodb512/adodb-active-record.inc.php(153): ADODB_Active_Record->UpdateActiveTable(false)
#1 /var/www/hrm/classes/SettingsManager.php(28): ADODB_Active_Record->__construct()
#2 /var/www/hrm/server.includes.inc.php(92): SettingsManager->getSetting('System: Do not ...')
#3 /var/www/hrm/login.php(5): include('/var/www/hrm/se...')
#4 /var/www/hrm/app/login.php(3): include('/var/www/hrm/lo...')
#5 {main}
  thrown in /var/www/hrm/adodb512/adodb-active-record.inc.php on line 405
```

**Comment by thilinah** [comment]
Can you check if db connection details are correct?

**Comment by professormahi** [comment]
Install has been done successfully! and All tables are there in the database

**Comment by thilinah** [comment]
If the application works and you are only getting this error time to time you need to check the stability of the connection between your DB and app. If not please let me know you web server details and mysql version so we can try to reproduce this issue.
